name: skyblock
version: '${version}'
main: me.dess1rous.skyblock.Main
depend: [Citizens]

commands:
  generationVoid:
    description: make a void
    usage: /generationvoid
  is:
    description: create a island
    usage: /is
  spawn:
    description: tp spawn
    usage: /spawn
  shop:
    description: open shop
    usage: /shop